# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
import = ["~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"]

# Font configuration
[font]
size = 15

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "MediumItalic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "BoldItalic"

[window]
decorations = "none"
