# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
general.import = [
    "~/.config/alacritty/themes/gruvbox_material_medium_dark.toml",
]

# Font configuration
[font]
size = 18

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Medium"
# family = "Iosevka Nerd Font Mono"
# style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bol"
# family = "Iosevka Nerd Font Mono"
# style = "Medium"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Medium"
# family = "Iosevka Nerd Font Mono"
# style = "Regular"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "BoldItalic"
# family = "Iosevka Nerd Font Mono"
# style = "Medium"

[window]
decorations = "none"

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" },
    { key = "B", mods = "Control|Shift", action = "ReceiveChar" },
    { key = "B", mods = "Command", action = "ReceiveChar" },
]
